export const metaKeywords = [
  "Family shop",
  "Online shopping",
  "Ecommerce",
  "Daily deals",
  "Family products",
  "Discounts",
  "Home essentials",
  "Family-friendly",
  "Affordable prices",
  "Quality products",
  "Convenience",
  "Variety of products",
  "Everyday items",
  "Family clothing",
  "Kitchen supplies",
  "Toys and games",
  "Electronics",
  "Home decor",
  "Personal care",
  "Health and wellness",
  "Baby products",
  "Kids' clothing",
  "School supplies",
  "Outdoor gear",
  "Pet supplies",
  "Garden essentials",
  "Sports equipment",
  "Travel accessories",
  "Books and magazines",
  "Gift ideas",
  "Party supplies",
  "Craft supplies",
  "Stationery",
  "Art supplies",
  "Family entertainment",
  "Seasonal products",
  "Holiday decorations",
  "Cooking utensils",
  "Bakeware",
  "Bedding and linens",
  "Furniture",
  "Home appliances",
  "Tech gadgets",
  "Fashion accessories",
  "Jewelry",
  "Beauty products",
  "Personalized items",
  "Family recipes",
  "DIY projects",
  "Product reviews",
  "Customer testimonials",
  "Free shipping",
  "Fast delivery",
  "Secure payments",
  "Easy returns",
  "Online discounts",
  "Shopping deals",
  "Special offers",
  "New arrivals",
  "Clearance sale",
  "Limited-time promotions",
  "Gift cards",
  "Customer support",
  "Online shopping experience",
  "User-friendly website",
  "Mobile shopping",
  "Responsive design",
  "Product search",
  "Product categories",
  "Shopping cart",
  "Wishlist",
  "Order tracking",
  "Product comparison",
  "Customer ratings",
  "Product recommendations",
  "Social media integration",
  "Newsletter subscription",
  "Promo codes",
  "Customer loyalty program",
  "Sustainable products",
  "Fair trade products",
  "Local products",
  "Community involvement",
  "Family values",
  "Parenting tips",
  "Family health",
  "Educational resources",
  "Family bonding",
  "Family activities",
  "Family travel",
  "Healthy recipes",
  "Parenting advice",
  "Family finances",
  "Work-life balance",
  "Family traditions",
  "Family support",
  "Family happiness",
  "Family well-being",
  "Family-friendly events",
  "Family celebrations",
  "Family memories",
  "Family home",
  "Family pets",
  "Family love",
  "Family unity"
]